pages: # the job must be named pages
  image: node:10
  stage: deploy
  script:
    - npm ci
    - npm run build
    - if [ -d "public" ]; then mv public public-vue; fi # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - pages # deploy only from branch named pages
